name: rest_client
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.15.1 <3.0.0'

dependencies:
  build_runner: ^2.1.0
  dartz: ^0.10.1
  dio: ^4.0.0
  freezed: ^1.1.0

dev_dependencies:
  freezed_annotation: ^1.1.0
  lints: ^1.0.0
  test: ^1.16.0
